name: Python package

on:
- push
- pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 3.12 # Match the version on the gateway node

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - id: fmt_and_lint
      run: |
        pip install black pylama
        black --check --diff .
        pylama
